### ISSUE TITLE
ArgumentError: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by DexterTheDragon** [jasmine/jasmine_junitxml_formatter#2]
Stacktrace:
```
~/.gem/ruby/2.1.7/gems/jasmine_junitxml_formatter-0.2.1/lib/jasmine/formatters/junit_xml.rb:39:in `done'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/formatters/multi.rb:13:in `block in done'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/formatters/multi.rb:13:in `each'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/formatters/multi.rb:13:in `done'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/runners/phantom_js.rb:51:in `run'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/ci_runner.rb:37:in `run'
~/.gem/ruby/2.1.7/gems/jasmine-2.4.0/lib/jasmine/tasks/jasmine.rake:47:in `block (2 levels) in <top (required)>'
```

It looks like the jasmine gem was changed to pass details to the done method. Relevant commit here https://github.com/jasmine/jasmine-gem/commit/eb2c7043e0086d078f82a01e882ddead38d8fdc6

**Comment by slackersoft** [comment]
Sorry about that, I've just release 0.3.0 that should no longer raise an Error. I'm working on a bit more of a restructuring of the grouping of the tests in the resulting file so it can also include properties for randomization
